---
title: "External Debt and Currency Crisis in Emerging Markets"
author: "New Group Project"
date: "April 21, 2019"
output: pdf_document
fontsize: 12pt
documentclass: article
number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\textbf{Members:}
\begin{itemize}
  \itemsep-.6em
  \item Liumin Chen (NetID: lc1077) - email: lc1077@georgetown.edu\
  \item Tingjie  Meng (NetID: tm1305) - email: tm1305@georgetown.edu\
\end{itemize}
\textbf{Github Repository:} https://github.com/TingjieMeng/New-Group-Project 

\section{Problem Statement}

Debts and credits are crucial both for the expansion of businesses and for economic development. However, when the growth of debts outpaces the growth of income, debts become a time bomb triggering crises. There are two types of debts: domestic debts denominated in the domestic currency and external debts denominated in foreign currencies. The history of financial crises tells us that countries with a high level of external debt are especially vulnerable to capital outflows and thus exchange rate fluctuations. As Ray Dalio describes in <zPrinciples for Navigating Big Debt Crisis>, such an event is called an inflationary depression.

One classic example of a deflationary depression is the Argentina currency crises in the early 2000s. At that time, pegged exchange rates provided an implicit guarantee of exchange rate stability. It encouraged households, domestic banks, and non-financial firms to build up significant short-term debt denominated in US dollars while their revenues were in local currencies. When a sharp increase in capital outflow happened due to the domestic political riots, the local currency lost value and debtors could not repay their foreign debts. The defaults caused loss of credibility of Argentine debtors in the international capital market, which then caused the local currency value to further plunge.

Our project focuses on studying the link between external debt and currency crisis in Emerging Market Economies (EME). EMEs typically face difficulties in issuing debts in local currency because their local financial markets are underdeveloped. Thus they are more likely to hold a significant portion of external debt in the total debt portfolio compared to developed economies. Specifically, we explore factors that strengthen or weaken the link between external debt and currency crisis in EMEs and use the patterns we find to predict the possibility of a currency crisis happening in future years. Our findings can serve as policy guidance for external debt management for central bank policymakers in emerging markets.

\section{Data Source}

Data sources for this study are as follows: the World Bank Open Data, the International Monetary Fund (IMF) Open Data, and the Polity IV Project conducted by the Center for Systemic Peace. 

\section{How to Obtain Data}

All three data sources are publicly available. The World Bank and IMF APIs can be installed in R, and the Polity IV Project data can be conveniently downloaded as a csv package.  

\section{Potential Issues}

First, since our project focuses on EMEs, it is anticipated that the dataset will contain many missing values and reporting bias. It is more difficult to obtain macroeconomic data on less developed countries because of bureaucratic mismanagement and officials' incentive to inflate their economic data. 

Second, domestic political instability is an important trigger of the bond selloff and capital outflow. However, we have not found an effective and direct measure of political stability. The Polity Score published by the Center for Systemic Peace is the closest measure we found, but it only gauges the level of democracy, not the level of political stability. This introduces bias into our model, as countries like China are assigned low polity scores but in fact have stable political systems.

