---
title: "External Debt and Currency Crisis in Emerging Markets"
author: "New Group Project"
date: "April 21, 2019"
output: pdf_document
fontsize: 12pt
documentclass: article
number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\textbf{Members:}
\begin{itemize}
  \itemsep-.6em
  \item Liumin Chen (NetID: lc1077) - email: lc1077@georgetown.edu\
  \item Tingjie  Meng (NetID: tm1305) - email: tm1305@georgetown.edu\
\end{itemize}
\textbf{Github Repository:} https://github.com/TingjieMeng/New-Group-Project 

\section{Problem Statement}

Our project focuses on studying the link between external debt and currency crisis in Emerging Market Economies (EME). Specifically, we explore factors that strengthen or weaken the link between external debt and currency crisis in EMEs and use the patterns we find to predict the possibility of a currency crisis happening in future years. Our findings can serve as policy guidance for external debt managing for central bank policy makers in emerging markets.

\section{Testable Hypotheses}



\section{Data Analysis Tools}




\section{Products}

There will be three kinds of final products. First, we produce data visualizations. 
Second, we produce three machine learning models. 
Third, we produce a statistical probit model. 