---
title: "External Debt and Currency Crisis in Emerging Markets"
author: "New Group Project"
date: "April 25, 2019"
output: pdf_document
number_sections: true
fontsize: 12pt
documentclass: article
---



Pr(Currency Crisis = 1) = φ(β0 + β1(External debt to GNI)i,t + β2(Polity2)i,t + β3(US 3m yield)i + β4(lag GDP per capita)i,t + β5(lag reserves to external debt)i,t + yeari + countryt + εi,t) -------- ??to be shared with professor

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\textbf{Members:}
\begin{itemize}
  \itemsep-.6em
  \item Liumin Chen (NetID: lc1077) - email: lc1077@georgetown.edu\
  \item Tingjie  Meng (NetID: tm1305) - email: tm1305@georgetown.edu\
\end{itemize}
\textbf{Github Repository:} https://github.com/TingjieMeng/New-Group-Project 

\section{Problem Statement}

Debts and credits are crucial both for the expansion of businesses and for economic development. However, when the growth of debts outpaces the growth of income, debts become a time bomb triggering crises. There are two types of debts: domestic debts denominated in the domestic currency and external debts denominated in foreign currencies. The history of financial crises tells us that countries with a high level of external debt are especially vulnerable to capital outflows and thus exchange rate fluctuations. As Ray Dalio describes in <Principles for Navigating Big Debt Crisis>, such an event is called an inflationary depression.

Classic examples of a deflationary depression are the Tukish currency crises in the early 2000s and 2018. Since the 1980s, Turkey has been heavily dependent on foreign investments to fund its huge current account deficits, especially in the capital-intensive construction sector. Thus its economy is fragile to any internal or external shock that can lead to foreign capital outflow on a large scale. In 2001, foreign investors quickly withdrew capital from Turkey amid political tensions and tightening fiscal policies by the Turkish government, which caused the value of Turkish lira to plunge. The history repeats itself. In 2018, due to domestic instability and tightening monetary policies from major central banks, Turkey saw a year-over-year decline of foreign investments by 9,500 basis points. Without sufficient foreign capital to support its weak economy, the Turkish lira soon began drastically losing value, leaving many companies unable to serve their foreign currency debts.

Our project focuses on studying the link between external debt and currency crisis in Emerging Market Economies (EME). As shown in Turkey's crises, over-dependence on external financing can be extremely dangerous for EMEs in the long run. However, EMEs typically face difficulties in issuing debts in local currency because their local financial markets are underdeveloped. Thus they are more likely to hold a significant portion of external debt in the total debt portfolio compared to developed economies. Specifically, we explore factors that strengthen or weaken the link between external debt and currency crisis in EMEs and use the patterns we find to predict the possibility of a currency crisis happening in future years. Our findings can serve as policy guidance for external debt management for central bank policymakers in emerging markets.


\section{Research Design}
* dataset
A time series dataset of 46 developing countries from 1995 to 2015
* data source
Data sources for this study are as follows: the World Bank Open Data, the International Monetary Fund (IMF) Open Data, and the Polity IV Project conducted by the Center for Systemic Peace. All three data sources are publicly available. The World Bank and IMF APIs can be installed in R, and the Polity IV Project data can be conveniently downloaded as a csv package.  
* Variable Description
Dependent variable: possibility of a currency crisis happening, defined as a nominal depreciation of 15% within a year
Independent variable of interest: externaldebt/GNI
Control variable: GDP per capita, level of democracy, US 3-month treasury yield, foreign reserves/total external debt


\section{Methods}
* data visualization
Data visualization is used for getting a general understanding of the relationships between independent variables and dependent variables. It is also used as case studies of individual countries that experience a classic pattern of currency crises.
* mixed-effect logit model
The logit model in parameterization form is as follows: 
Pr(Currency Crisis = 1) = φ(β0 + β1(External debt to GNI)i,t + β2(Polity2)i,t + β3(US 3m yield)i + β4(lag GDP per capita)i,t + β5(lag reserves to external debt)i,t + yeari + countryt + εi,t)
* machine learning techniques 
We use several models including K nearest neighbours, CART, and Random Forest. After comparison, we choose the one model specification with the best model fit. 


\section{Results}
* data visualization
......
* mixed-effect logit model
* machine learning techniques 
We use several models including K nearest neighbours, CART, and Random Forest. After comparison, we choose the one model specification with the best model fit. 

\section{Lessons Learned}
* Data source
* Missing value: on Argentina
* Coding issues
Potentially more variables to include: economic structure, exchange rate regime, etc.
Polity score: not the most ideal measure of political stability
Using machine learning methods to increase prediction power






